# Generated by Django 3.2.9 on 2021-11-16 10:13

import adminCT.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCT',
            fields=[
                ('A_id', models.AutoField(primary_key=True, serialize=False)),
                ('A_name', models.CharField(max_length=100)),
                ('A_email', models.EmailField(max_length=255, unique=True)),
                ('A_password', models.CharField(max_length=255)),
                ('A_phonenumber', models.CharField(max_length=10, validators=[adminCT.models.validate_phone_number])),
            ],
            options={
                'db_table': 'AdminCT',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=75)),
                ('cemail', models.EmailField(max_length=255, unique=True)),
                ('cpassword', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='cust_phone_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10, validators=[adminCT.models.validate_phone_number])),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminCT.customers')),
            ],
            options={
                'db_table': 'Cust_phone_number',
            },
        ),
        migrations.CreateModel(
            name='cust_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=255, null=True)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=75, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminCT.customers')),
            ],
            options={
                'db_table': 'Cust_address',
            },
        ),
    ]
