# Generated by Django 3.2.9 on 2021-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_Login',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cust_Login',
            },
        ),
    ]
