# Generated by Django 3.2.9 on 2021-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0002_cust_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
