# Generated by Django 3.2.9 on 2021-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0003_customers_isauthenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
    ]
