# Generated by Django 3.2.9 on 2021-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0005_remove_customers_isauthenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
