# Generated by Django 3.2.9 on 2021-11-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0006_customers_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='last_login',
        ),
    ]
