# Generated by Django 3.2.9 on 2021-11-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0007_remove_customers_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminct',
            name='isAuthenticated',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='isAuthenticated',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
