# Generated by Django 3.2.9 on 2021-11-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0008_auto_20211118_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_login',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
