# Generated by Django 3.2.9 on 2021-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0009_customers_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminct',
            name='last_login',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
