# Generated by Django 3.2.9 on 2021-11-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0011_auto_20211118_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
