# Generated by Django 3.2.9 on 2021-11-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0014_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
