# Generated by Django 3.2.9 on 2021-11-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0016_auto_20211118_2019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stocks',
            table='Stocks',
        ),
    ]
