# Generated by Django 3.2.9 on 2021-11-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0017_alter_stocks_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
