# Generated by Django 3.2.9 on 2021-11-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0019_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='sqty',
            field=models.IntegerField(max_length=255),
        ),
    ]
