# Generated by Django 3.2.9 on 2021-11-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0021_alter_stocks_sqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='simage',
        ),
    ]
