# Generated by Django 3.2.9 on 2021-11-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCT', '0023_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CART',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('sid', models.IntegerField()),
            ],
            options={
                'db_table': 'CART',
            },
        ),
    ]
